//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUTTING_DRYING
    {
        public int id { get; set; }
        public Nullable<double> ss_temper { get; set; }
        public Nullable<System.DateTime> time_update { get; set; }
        public string ss_humidity { get; set; }
        public Nullable<double> value_humidity { get; set; }
        public Nullable<double> value_temper { get; set; }
        public Nullable<int> timer1 { get; set; }
        public Nullable<int> timer2 { get; set; }
    }
}
