//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEELING
    {
        public int id { get; set; }
        public string ss_pressure { get; set; }
        public Nullable<double> value_pressure { get; set; }
        public Nullable<System.DateTime> time_update { get; set; }
        public string ss_speeddrum { get; set; }
        public Nullable<int> timer_action { get; set; }
        public Nullable<double> Value_speeddrum { get; set; }
        public Nullable<int> TimerAction { get; set; }
    }
}
